import logging
from typing import Optional
from google import genai

try:
    from app.config import GEMINI_API_KEY, GEMINI_MODEL_NAME
except ModuleNotFoundError:
    from backend.app.config import GEMINI_API_KEY, GEMINI_MODEL_NAME

logger = logging.getLogger(__name__)

_client: Optional[genai.Client] = None


def get_genai_client() -> Optional[genai.Client]:
    """
    Lazy-load Gemini GenAI client.
    Returns None if GEMINI_API_KEY is not configured.
    """
    global _client
    if _client is not None:
        return _client

    if not GEMINI_API_KEY:
        logger.warning("GEMINI_API_KEY is not configured in the .env file.")
        return None

    try:
        _client = genai.Client(api_key=GEMINI_API_KEY)
        return _client
    except Exception as e:
        logger.error(f"Failed to initialize GenAI client: {e}")
        return None


def generate_answer(
    question: str,
    context: list[dict]
) -> str:
    """
    Generate a readable answer using Gemini and retrieved PDF evidence.
    """
    if not context:
        return "No relevant information was found in the uploaded documents."

    client = get_genai_client()
    if not client:
        return (
            "ResearchPilot cannot generate an answer because GEMINI_API_KEY is "
            "missing or not configured in your .env file."
        )

    evidence = "\n\n".join(
        [
            (
                f"Document: {item.get('document_name', 'Unknown')}\n"
                f"Page: {item.get('page_number', 1)}\n"
                f"Evidence:\n{item.get('text', '')}"
            )
            for item in context
        ]
    )

    prompt = f"""You are ResearchPilot, a document research assistant.

Answer the user's question using ONLY the evidence provided below.

Do not invent information.
Do not use outside knowledge.
If the evidence does not contain enough information, say that the documents do not provide enough information.

Write a clear, concise, understandable answer.
You may use Markdown formatting such as:
- bullet points
- numbered lists
- bold text
- short headings

Do not include source labels, page numbers, or document names in your answer. Those are handled separately by the application.

User question:
{question}

Retrieved evidence:
{evidence}
"""

    try:
        response = client.models.generate_content(
            model=GEMINI_MODEL_NAME,
            contents=prompt
        )
        return response.text or "No response generated by the model."

    except Exception as error:
        error_message = str(error)
        logger.error(f"Gemini API error: {error_message}")

        if "429" in error_message or "RateLimitError" in error_message:
            return (
                "ResearchPilot is temporarily rate-limited by the Gemini API. "
                "Please wait a moment and try again."
            )

        return (
            f"ResearchPilot could not generate the answer because the AI service "
            f"returned an error: {error_message}"
        )